name: Release
on:
  push:
    branches:
      - master
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  release:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build dependencies
        run: npm run build
      - name: Commit and push changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add dist
          git commit -m "Build dist files"
          git push origin master
          git fetch origin
      - name: Install semantic release
        shell: bash
        # Note: Remove the alias line once https://github.com/semantic-release/github/pull/487 is merged
        run: |-
          npm install -g \
            @semantic-release/github@npm:@achingbrain/semantic-release-github@0.0.1 \
            semantic-release \
            @semantic-release/exec \
            @semantic-release/git
      - name: Release
        shell: bash
        # Note: semantic-release can partially fail, but still tag (that's important)
        # so make a best effort to continue in case of error
        run: npx semantic-release || true
